AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - "vendor/**/*"
    - "**/tmp/**/*"
    - "gemfiles/*"


# Style ------------------------------------

Style/FileName:
  Exclude:
    - lib/middleman-sprockets.rb

Style/MultilineOperationIndentation:
  EnforcedStyle: aligned

Style/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/MultilineOperationIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
      '%':  '{}'
      '%w': '[]'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

# Metrics ----------------------------------

Metrics/LineLength:
  Max: 128

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Naming -----------------------------------

Naming/MemoizedInstanceVariableName:
  Enabled: false

# Lint -------------------------------------

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/AmbiguousRegexpLiteral:
  Exclude: ["features/step_definitions/**/*"]
