language: ruby
cache: bundler
sudo: false
env: TEST=true

rvm:
  - 2.2.6
  - 2.3.3
  - ruby-head

gemfile:
  - gemfiles/middleman-4.1.gemfile

matrix:
  include:
  - rvm: 2.3.3
    gemfile: gemfiles/middleman-head.gemfile
    env: SKIP_ASSET_HASH=true MIDDLEMAN_HEAD=true
  - rvm: 2.3.3
    gemfile: gemfiles/middleman-4.0.gemfile
    env: SKIP_ASSET_HASH=true
  - rvm: 2.3.3
    gemfile: gemfiles/sprockets-4.0.gemfile
    env: SKIP_ASSET_HASH=true

  allow_failures:
    - rvm: ruby-head
    - rvm: 2.3.3
      gemfile: gemfiles/sprockets-4.0.gemfile
